### ISSUE TITLE
[QA] Yunjae

### ISSUE THREAD

**Issue by qodhrkawk** [Polaris-Sopterm/Polaris-iOS#52]
- [x] [Todo 3개 이상일때 스크롤 ](https://ordinary-sorrel-60f.notion.site/3-Todo-02f1c738478942e09f8cd353a9b203a4)
- [x] [돌아보기: 표시할 별 수정](https://ordinary-sorrel-60f.notion.site/b4325068fd65418cb73b60e5098b3c0c)

**Comment by dongminyoon** [comment]
여기도 전부 해결되었으면 라벨 v1.0.0 붙이고 close 부탁드릴게요~
현재 이슈에 링킹된 PR이 따로 없어서 이슈만으론 크게 의미가 없어보여서 다음에 더 디벨롭 진행하면 규칙을 정하는 것이 좋을 것 같습니다
