### ISSUE TITLE
[Design QA] Yunjae

### ISSUE THREAD

**Issue by qodhrkawk** [Polaris-Sopterm/Polaris-iOS#53]
- [x] [홈화면 하단 선택시 셀 깨짐](https://ordinary-sorrel-60f.notion.site/UI-b47b11eed9cf4c31b3a85ffe9fcfb19f)
- [x] [홈화면 다섯째주 대응](https://ordinary-sorrel-60f.notion.site/b8e826b971414f10a680bbb00e290507)
- [x] [회고 텍스트 입력 버튼 추가](https://ordinary-sorrel-60f.notion.site/e962f0fa4fcd430d86175a846406b149)
- [x] [회고 SE 대응](https://ordinary-sorrel-60f.notion.site/SE-36df11ba9d9249c2b3342efa60cdd7fd)

**Comment by dongminyoon** [comment]
전부 해결되었으면 라벨 1.0.0 붙이고 issue close 부탁드릴게요~
